<a href="https://colab.research.google.com/github/AliZaiN-157/Tensorflow-Practice/blob/main/LinearReg_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf 
import random

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
## X Independent Variable ( X )

X = tf.constant([1,2,3,4,5,6], tf.float32)
X

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [ ]:
## Y Dependent Variable ( Y )

Y= tf.constant([100,200,300,400,500,600], tf.float32)
Y

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([100., 200., 300., 400., 500., 600.], dtype=float32)>

### Y = wX + b
where :
- Y = predict
- X = Input
- w = Weights
- b = Bias

In [ ]:
w = tf.Variable(tf.constant(random.uniform(0,1)))

b = tf.Variable(tf.constant(random.uniform(0,1)))


In [ ]:
def predict(X,w,b):
    y_hat = tf.multiply(w, X) + b
    return y_hat

In [ ]:
prediction = predict(X,w,b)
print(prediction)

tf.Tensor([1.6306281 2.3255074 3.0203867 3.7152658 4.410145  5.1050243], shape=(6,), dtype=float32)


In [ ]:
#Train Model loss function will be MeanSquareError(mse)

def loss(y_hat, Y):
    squared_error = tf.square(y_hat - Y)
    mse = tf.reduce_mean(squared_error)
    return mse 

In [ ]:
print(loss(prediction, Y))

tf.Tensor(148916.58, shape=(), dtype=float32)


In [ ]:
def train(X, Y, w, b):
    Learning_Rate = 0.05

    with tf.GradientTape() as t:

        y_hat = predict(X, w, b)
        step_loss = loss(y_hat, Y)

    grad_w, grad_b = t.gradient(step_loss, [w,b])

    w.assign_sub(Learning_Rate * grad_w)  
    b.assign_sub(Learning_Rate * grad_b)  



In [ ]:
for epoch in range(2000):

    train(X, Y, w, b)

In [ ]:
prediction = predict(X, w, b)
print(prediction)

tf.Tensor([100.      199.99998 299.99994 399.99994 499.99994 599.9999 ], shape=(6,), dtype=float32)


In [ ]:
print(loss(prediction, Y))

tf.Tensor(4.3849773e-09, shape=(), dtype=float32)
