<a href="https://colab.research.google.com/github/AliZaiN-157/Tensorflow-Practice/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow --upgrade --quiet

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.4.1


## **Scalar**
 
A scalar is a real number that can be expressed using a quantitative value.

e.g : 
- 10Kg
- 5 feet

## **Tensors**

Tensors are multi-dimensional arrays with a uniform data type.

Rank of tensors determines the number of dimensions of an array.

1. Scalar is a "Rank-0" tensor since it has magnitude but no dimensionality

2. Vector is a "Rank-1" tensor since it has a single dimension, also known as 
"**1-D tensor**".

3. Matrix is a "Rank-2" tensor since it has a two dimension, also known as 
"**2-D tensor**".



In [ ]:
constant = tf.constant

In [ ]:
scalar = constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
print(scalar.shape)
print(scalar.dtype)
print(scalar.numpy())

()
<dtype: 'int32'>
3


In [ ]:
Rank_1D = constant([1,2,3,4,5])
print(Rank_1D)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
Rank_2D = constant([[1,2,3,4],[5,6,7,8]])
print(Rank_2D)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [ ]:
Rank_3D = constant([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[9,10,11,12]]])
print(Rank_3D)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 5  6  7  8]
  [ 9 10 11 12]]], shape=(2, 2, 4), dtype=int32)


#### Different Types of Tensor

In [ ]:
print(tf.ones([2,2,4]))

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 2, 4), dtype=float32)


In [ ]:
print(tf.zeros([2,2,4]))

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 2, 4), dtype=float32)


In [ ]:
print(tf.eye(3,3))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.fill([2,2], 4))

tf.Tensor(
[[4 4]
 [4 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.linspace(0,9,5)) # linspace(start,stop,evenlydistributed)

tf.Tensor([0.   2.25 4.5  6.75 9.  ], shape=(5,), dtype=float64)


In [ ]:
print(tf.range(0,9,2)) # range(start,stop,steps)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
x = tf.Variable(tf.constant([1,2,3]))
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
#assign()

x.assign(tf.constant([4,5,6]))
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

#### Tensor Operations in Tensorflow




In [ ]:
t1= constant([1,2,3])
t2= constant([4,5,6])
print("tensor 1 =>",t1,"\ntenors 2 =>",t2)

tensor 1 => tf.Tensor([1 2 3], shape=(3,), dtype=int32) 
tenors 2 => tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [ ]:
t3 = tf.add(t2,t1)
print(t3) # both will give same result
print(t1 + t2)
## similarly with subtract(), multiply(), divide().

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [ ]:
t4 = tf.square(t2)
print(t4)
## similarly with reduce_mean()
t6 = tf.reduce_mean(t2)
print(t6)
print(t4 + t6)

tf.Tensor([16 25 36], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([21 30 41], shape=(3,), dtype=int32)


In [ ]:
##Complex Operations

t5 = t1 + tf.reduce_mean(t2) + tf.square(t2)
t5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 32, 44], dtype=int32)>